### ISSUE TITLE
mate30 实测，开始就结束了。。。大佬怎么办呢？

### ISSUE THREAD

**Issue by BattleSensor** [YBQ789/taobao-1212#3]

**Comment by BattleSensor** [comment]
重新启动，好了，可以运行了，我看看能不能有收益

**Comment by While-Shark** [comment]
我也是，开始就结束，怎么个重新启动法？

**Comment by BattleSensor** [comment]
> 我也是，开始就结束，怎么个重新启动法？

让代码自己启动淘宝，就行了，金币可以全额领取，很棒！

**Comment by try90** [comment]
我刚更新了脚本，可以试试新的脚本，实测3次完美运行

**Comment by BattleSensor** [comment]
> 我刚更新了脚本，可以试试新的脚本，实测3次完美运行

没更新也是完美运行，我已经做完两天任务了！给力大佬！
