### ISSUE TITLE
脚本的正确启动方法

### ISSUE THREAD

**Issue by While-Shark** [YBQ789/taobao-1212#4]

**Comment by try90** [comment]
其实是不需要手动打开淘宝的，脚本会自动打开

**Comment by catseie** [comment]
> 其实是不需要手动打开淘宝的，脚本会自动打开
昨天还可以，今天直接启动脚本，之后淘宝自动打开，马上就弹回autojs了，

**Comment by catseie** [comment]
> > 其实是不需要手动打开淘宝的，脚本会自动打开
> > 昨天还可以，今天直接启动脚本，之后淘宝自动打开，马上就弹回autojs了，

对了，我是用的蓝叠模拟器，淘宝9.0.0

**Comment by try90** [comment]
> > > 其实是不需要手动打开淘宝的，脚本会自动打开
> > > 昨天还可以，今天直接启动脚本，之后淘宝自动打开，马上就弹回autojs了，
> 
> 对了，我是用的蓝叠模拟器，淘宝9.0.0

这个应该是模拟器的问题了
